### PR TITLE
[WIP] rework/refactor 

### PR DESCRIPTION
**Pull request by jkowalleck**
RE:  https://github.com/CycloneDX/cyclonedx-php-composer/pull/10#issuecomment-774524762

this is a messy branch, but i think its worth to take a look. 
basically Work In Progress.

highlights:
* more CI chain
* a demo in CI chain
* more QA tools
* more structured tests (work in progress)
* new: deserializer is implemented and showcased in the functional tests
* (de)serializer still handcrafted.

:construction:   my person todo-list to get from WIP to ready state: https://github.com/jkowalleck/cyclonedx-php-composer/issues/2

----

:information_source: **STATUS**
* lots of the QA features of this PR were merged into master in separate small chunks already.
* the demo similar to the one of this rework was merged into master lately (see #58)
* core rework/refactoring is still unfinished
* --> parts f this PR are unnecessary now, since they were integrated into master already.
* --> this PR will be closed soon, and more recent and rebased version will be opened as a draft, then.

### CODE REVIEW

**Comment by coderpatros** [comment]
There's a lot to go through. But it's looking good so far.

Only thing that stands out to me is the tools directory. Can you explain the reason for it and the items in it?

**Comment by jkowalleck** [comment]
@coderpatros 
thanks for having a look. please donit spend too much time with the review at this point. it is still WIP and there is a long way to go, still.

regarding the `tools`:

in contrast to libraries or frameworks that are used for the development - such as phpunit, json-schema-parsers and others -
the tools are standalone programs that are not required to run or write the code. there is no actual need to have them installed via composer, neither do we actually need their transitive dependencies.
the idea was of having a `tools` folder was, that standalone programs/projects we use during development are decoupled from the actual project, its `composer.json` and each other.

the tools were installed via [PHIVE] and maintained with PHIVE - while phive is also one of the files in the`'tools'`folder and capable of maintaining itself..

items in `tools` folder are (current staus): 
* `composer` version 2 -- since we depend on it during development and CI tests. 
  we should have a pinned stable version available for tests, to not depend on an unknown version that is shipped with a CI engine.
* [`composer-unused`](https://github.com/composer-unused/composer-unused)
  to test tat we did not add unneeded dependencies to our own `composer.json`
* [`phive`][PHIVE] 
* [`php-cs-fixer`](https://github.com/FriendsOfPhp/PHP-CS-Fixer)
  to bring code to a common coding style, add the license-comment  in the head of each php file, and so on.  
  configuration in `.php_cs.dist`
* [`psalm`](https://psalm.dev)
  for static code analysis.   
  configured in `psalm.xml.dist`.  
  php depends heavily on it, since non-bugs/typing-errors would be detected on actual code-execution in tuntime, otherwise.

i decided to use phpunit as a composer-dependency since PHPUnit is primarily a framework, not a tool.

[PHIVE]: https://phar.io/

**Comment by coderpatros** [comment]
Do we need to have those checked into source control?

Could we gitignore the tools directory and have a `download-tools.sh` script or something like that?

Their inclusion is a bit opaque otherwise.

**Comment by jkowalleck** [comment]
> Do we need to have those checked into source control?
> 
> Could we gitignore the tools directory and have a `download-tools.sh` script or something like that?
> 
> Their inclusion is a bit opaque otherwise.

@coderpatros  could you explain the benefit?
seams cumbersome to have a setup-script that needs to be called by every developer, and every CI run.

**Comment by coderpatros** [comment]
The pedigree and provenance of those files is really opaque including them like this.

They can be cached for CI runs. So not too worried about that.

**Comment by jkowalleck** [comment]
> 
> 
> The pedigree and provenance of those files is really opaque including them like this.
> 
> They can be cached for CI runs. So not too worried about that.

I am not native English speaker, @coderpatros, so maybe i dont get it.
What does "pedigree and provenance of those files is really opaque" mean?

tools were downloaded via [phive](https://phar.io/)  according to the description in `.phive/phars.xml`(https://github.com/jkowalleck/cyclonedx-php-composer/blob/php_ge_73/.phive/phars.xml)
Did this help to make it non-opaque?

plus, there is a prominent example which does exactly the same: PHPUnit - the framework everybody uses to test php software.
see https://github.com/sebastianbergmann/phpunit

**Comment by coderpatros** [comment]
Essentially I mean is it really what we say it is?

It's hard to verify that by just looking at the pull request. Where as if there is a script that is downloading/building it directly from upstream that is much easier to verify.

I haven't done any serious work in the PHP ecosystem for some time. So there may be tooling available, that I am unaware of, to easily verify the contents of those files are unmodified from the upstream sources.

**Comment by jkowalleck** [comment]
I see.

with this in mind, i will think of a solution.
regards caching: you are completely right. using githubs caching-action based on an MD5 on phive's lock file, this should be doable.

will come back with a solution later.
Will do a first test in the upcoming PR of https://github.com/package-url/packageurl-php

**Comment by jkowalleck** [comment]
@coderpatros 

RE: https://github.com/CycloneDX/cyclonedx-php-composer/pull/18#issuecomment-789162995
tools are now managed by composer, maintainable by dependabot.

since https://github.com/package-url/packageurl-php is implemented in a feature complete version,
i will continue working on this implementation of `cyclonedx-php-composer`.

will come back, when i have a version i am pleased with, so we can discuss splitting the composer-plugin 
and the actual models/business-logic/etc.

**Comment by jkowalleck** [comment]
QA parts of this are done via #23 

rest will be split into smaller chunks and come as a followup, after some planning was done.

**Comment by jkowalleck** [comment]
demo was integrated via #58

**Comment by jkowalleck** [comment]
closed in favor of #76

**Pull request closed without merging**
