### PR TITLE
Add initial JSON support

### PR DESCRIPTION
**Pull request by coderpatros**

### CODE REVIEW

**Comment by jnkowa-gfk** [comment]
Hello @coderpatros ,
@nscuro ,  @stevespringett

Is there any chang having this reworked/rebased onto latest master  
and have a release v1.2 ?

**Comment by jkowalleck** [comment]
notes:
* list of known licenses: https://raw.githubusercontent.com/spdx/license-list-data/master/json/licenses.json
* some validation is needed, just as #15 introduces them
* since JSON does not have an enum restriction (unlike XML) it might be easiest to use ` composer/spdx-licenses` as a dependency.

**Comment by jkowalleck** [comment]
@stevespringett should the list of known licenses (see https://github.com/CycloneDX/cyclonedx-php-composer/pull/15#issuecomment-774342699) applied to JSON, too?
or should https://raw.githubusercontent.com/spdx/license-list-data/master/json/licenses.json be use for JSON?

**Comment by coderpatros** [comment]
@jkowalleck I'm going to close this PR. I deleted my fork so it was easier to just push up a new branch and create a new PR #16

**Pull request closed without merging**
